name: regularized-linear-regression-env
channels:  
    - conda-forge
dependencies:  
    - python=3.7.6
    - numpy=1.22.2 # originally: 1.24.3
    - pandas=1.4.1
    - Matplotlib=3.5.1 # 3.8.4
    - scikit-learn=0.20.3
    - seaborn=0.11.2 # working with 0.13.0
    - jupyter_core=5.7.2
    - ipython=8.12.2
    - ipykernel=6.29.5
    - jupyter_client=8.6.0
    - nbconvert=7.16.4
    - ipywidgets=8.1.2
    - nbformat=5.10.4
    - traitlets=5.14.3
    - jupyter_server=2.14.1
    - jupyterlab=4.2.5
    - nbclient=0.8.0
    - jupyterlab-git=0.50.1
    - jupyterlab-variableinspector=3.2.4
    - jupyterlab_code_formatter=3.2.4
    - jupyterlab-spellchecker   0.8.4
    - jupyterlab_pygments
    - jupyterlab_widgets
    - markdown-it-py=3.0.0
    - nbconvert-core=7.16.4
    - nbconvert-pandoc =7.16.4
    - nbdime=4.0.2
    - folium=0.18.0
    - flake8-markdown
    - isort
    - black
    - nodejs
    - markdown-it-py
    - nbdime
    # - nbpreview